baseURL = "https://dimak1561.github.io/"
languageCode = "ru"                      
title = "Мой сайт"                       
theme = "ananke"                         
buildDrafts = false                    


[params]                                 
  author = "Karmanov Dmitrii"
  description = "Описание сайта"
  showReadingTime = true                 
  showPostNavLinks = true

[menu]                                   
  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "О себе"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Блог"
    url = "/post/"
    weight = 3